permalink   : /:title/
markdown    : kramdown
highlighter : pygments

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

baseurl: "" # change to empty string ""
domain_name: joeljacquez.com
google_analytics: UA-85052080-1

source:      source
destination: _site

# cover: /assets/images/header-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: Joel Jacquez
title: Joel Jacquez | Web Developer
description: "Developer Front-end/NodeJS,  Responsive Desing, HTML5, CSS3, JavaScript"
meta_description: "Developer Front-end/NodeJS,  Responsive Desing, HTML5, CSS3, JavaScrip"
meta_keywords: "site, website, frontend, front-end, html5, css3, javascript, jquery, seo, performance"
url: http://joeljacquez.com
production_url: http://joeljacquez.com
repo: https://github.com/JoelJacquez/blog-personal
disqus_shortname: "joeljacquez"
rss_path: source/
author:
  name      : Joel Jacquez
  image     : /assets/images/author.jpg
  email     : joel@gmail.com
  url       : https://joeljacquez.github.io
  facebook  : https://www.facebook.com/cryptt3r
  twitter   : https://twitter.com/cryptt3r
  github    : https://github.com/joeljacquez
  linkedin  : https://mx.linkedin.com/in/jacquez
  bio       : "Desarrollador web, entusiasta de la tecnología, buscando siempre la mejor solución acompañada de un buen cafe"

# thought
thought:
  text: I have no special talent. I am only passionately curious.
  author: Albert Einstein

# Plugin: jekyll-assets
assets:
  dirname: /assets
  baseurl: /assets/ # change to /assets/
  sources:
    - assets/images
    - assets/fonts
    - assets/css
    - assets/js
  cache: true
  gzip: [ text/css, application/javascript ]

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: all

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
